name: GsAutoRestart
version: '1.0'
main: ru.gsdev.gsautorestart.GsAutoRestart
api-version: '1.16'
authors: [RuilloYT]
description: Плагин для автоматического рестарта сервера с настраиваемыми уведомлениями
commands:
  autorestart:
    description: Управление автоматическим рестартом сервера
    usage: /autorestart <время[s,m,h]> или /autorestart отмена
    permission: autorestart.use
    aliases: [ar]
permissions:
  autorestart.use:
    description: Разрешает использование команды /autorestart
    default: op